# Generated by Django 4.2.7 on 2025-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID or identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Natural language question asked by user"
                    ),
                ),
                (
                    "sql",
                    models.TextField(
                        blank=True, help_text="Generated SQL query", null=True
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("row_count", models.IntegerField(default=0)),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
