from ignis.models import (
    KpiOverallEquipmentEfficiencyData,
    KpiDefectRateData,
    KpiEnergyEfficiencyData,
    KpiDowntimeData,
    KpiMeanTimeBetweenFailuresData,
    KpiYieldData,
    KpiResourceCapacityUtilizationData,
    KpiSafetyIncidentsReportedData,
    KpiCycleTimeData,
    KpiOutputRateData,
    KpiQuantityProducedData,
    KpiProductionEfficiencyData,
    KpiOnTimeDeliveryData,
    KpiFirstPassYieldData,
    KpiReworkRateData,
    KpiEnergyUsedData,
    KpiMaintenanceComplianceData,
    KpiMeanTimeToRepairData,
    KpiMeanTimeBetweenStoppagesData,
    KpiPlannedMaintenanceData,
    CoreProcessTapProcess,
    CoreProcessTapProduction,
    CoreProcessTapGrading,
    FurnaceConfigParameters,
    LogBookFurnaceDownTimeEvent,
    # Added: 4 missing tables for complete schema coverage
    FurnaceFurnaceconfig,
    PlantPlant,
    LogBookReasonMaster,
    LogBookDowntimeTypeMaster,
)

# List of models explicitly requested for the Chatbot context
RELEVANT_MODELS = [
    KpiOverallEquipmentEfficiencyData,
    KpiDefectRateData,
    KpiEnergyEfficiencyData,
    KpiDowntimeData,
    KpiMeanTimeBetweenFailuresData,
    KpiYieldData,
    KpiResourceCapacityUtilizationData,
    KpiSafetyIncidentsReportedData,
    KpiCycleTimeData,
    KpiOutputRateData,
    KpiQuantityProducedData,
    KpiProductionEfficiencyData,
    KpiOnTimeDeliveryData,
    KpiFirstPassYieldData,
    KpiReworkRateData,
    KpiEnergyUsedData,
    KpiMaintenanceComplianceData,
    KpiMeanTimeToRepairData,
    KpiMeanTimeBetweenStoppagesData,
    KpiPlannedMaintenanceData,
    CoreProcessTapProcess,
    CoreProcessTapProduction,
    CoreProcessTapGrading,
    FurnaceConfigParameters,
    LogBookFurnaceDownTimeEvent,
    # Added: 4 missing tables
    FurnaceFurnaceconfig,
    PlantPlant,
    LogBookReasonMaster,
    LogBookDowntimeTypeMaster,
]

# Descriptions to help the NLP understand the context of each table
TABLE_DESCRIPTIONS = {
    'kpi_overall_equipment_efficiency_data': 'KPI: Overall Equipment Efficiency (OEE) metrics',
    'kpi_defect_rate_data': 'KPI: Defect rate metrics',
    'kpi_energy_efficiency_data': 'KPI: Energy efficiency metrics',
    'kpi_downtime_data': 'KPI: Downtime duration metrics',
    'kpi_mean_time_between_failures_data': 'KPI: MTBF (Mean Time Between Failures) metrics',
    'kpi_yield_data': 'KPI: Production yield metrics',
    'kpi_resource_capacity_utilization_data': 'KPI: Resource capacity utilization metrics',
    'kpi_safety_incidents_reported_data': 'KPI: Safety incidents reported',
    'kpi_cycle_time_data': 'KPI: Cycle time analysis',
    'kpi_output_rate_data': 'KPI: Output rate metrics',
    'kpi_quantity_produced_data': 'KPI: Quantity produced metrics',
    'kpi_production_efficiency_data': 'KPI: Production efficiency metrics',
    'kpi_on_time_delivery_data': 'KPI: On-time delivery metrics',
    'kpi_first_pass_yield_data': 'KPI: First pass yield metrics',
    'kpi_rework_rate_data': 'KPI: Rework rate metrics',
    'kpi_energy_used_data': 'KPI: Total energy used metrics',
    'kpi_maintenance_compliance_data': 'KPI: Maintenance compliance metrics',
    'kpi_mean_time_to_repair_data': 'KPI: MTTR (Mean Time To Repair) metrics',
    'kpi_mean_time_between_stoppages_data': 'KPI: MTBS (Mean Time Between Stoppages) metrics',
    'kpi_planned_maintenance_data': 'KPI: Planned maintenance metrics',
    'core_process_tap_process': 'CORE PROCESS: Live furnace tap process data',
    'core_process_tap_production': 'CORE PROCESS: Live tap production data (weights, energy)',
    'core_process_tap_grading': 'CORE PROCESS: Tap grading and quality allocation',
    'furnace_config_parameters': 'CONFIGURATION: Furnace configuration parameters',
    'log_book_furnace_down_time_event': 'DOWNTIME LOGBOOK: Specific downtime events log',
    # Added: 4 missing tables
    'furnace_furnaceconfig': 'CONFIGURATION: Furnace master data (furnace_no, description, workshop)',
    'plant_plant': 'CONFIGURATION: Plant/site master data',
    'log_book_reason_master': 'DOWNTIME: Downtime reason codes and descriptions',
    'log_book_downtime_type_master': 'DOWNTIME: Downtime type classifications (planned, unplanned, etc.)',
}
